export const Brands = [
  'Alexander McQueen',
  'Alexander Wang',
  'Axel Arigato',
  'Balenciaga',
  'Balmain',
  'Bottega Veneta',
  'Burberry',
  'Cartier',
  'Casablanca',
  'Celine',
  'Chanel',
  'Chloe',
  'Christian Dior',
  'Christian Louboutin',
  'Coach',
  'Cotton Citizen',
  'Dolce & Gabbana',
  'Farfetch',
  'Fear of God - Essentials',
  'Fendi',
  'Gaia Léon',
  'Gianvito Rossi',
  'Givenchy',
  'Golden Goose',
  'Gucci',
  'Hermes',
  'Jacquemus',
  'Jimmy Choo',
  'Kate Spade',
  'Loewe',
  'Louis Vuitton',
  'Manolo Blahnik',
  'Mansur Gavriel',
  'MCM',
  'Michael Kors',
  'MiuMiu',
  'Moncler',
  'Moschino',
  'Mulberry',
  'Prada',
  'Saint Laurent',
  'Salvatore Ferragamo',
  'Ssense',
  'Stella McCartney',
  'Telfar',
  'Tom Ford',
  'Tory Burch',
  'Valentino',
  'Versace',
];
